/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/ayakkabi.glb
Author: smearballs (https://sketchfab.com/smearballs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/converse-shoe-4237f51cebe048119420c8a44be97b4f
Title: CONVERSE SHOE
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Ayakkabi({ customColors, ...props }) {
  // Yolu '/ayakkabi.glb' olarak değiştirin.
  // Bu, public klasörünün kökünü işaret eder.
  const { nodes, materials } = useGLTF('/ayakkabi.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.268}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.model_Material_u1_v1}
          material-color={customColors.ayakkabi}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.model_Material_u1_v1}
          material-color={customColors.ayakkabi}
        />
      </group>
    </group>
  )
}

// Preload için de yolu '/ayakkabi.glb' olarak güncelleyin.
useGLTF.preload('/ayakkabi.glb')